X-Backtory-Authentication-Id: 1111111111111111
X-Backtory-Authentication-Key: 2222222222222222
X-Backtory-Object-Storage-Id: 333333333333333

#domain: domain.com

#headers:
#  h1: v1
#  h3: v2

#parameters:
#  p1: v1
#  p2: v2